version: '3.7'
services:
  database:
    build: ./database
    ports:
      - "5432:5432"
  ingestor:
    build: ./ingestor
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://dirt:password@database:5432/dirt?ssl=false
      - ROOT_ADDRESS
      - INFURA_ENDPOINT
    depends_on:
      - database
    volumes:
      - ./tools/scripts:/usr/src/app/scripts
    command:
      - /bin/sh
      - -c
      - |
        ./scripts/wait-for-it.sh -s -t 30 database:5432
        npm start
  express:
    build: ./express
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ROOT_ADDRESS
      - INFURA_ENDPOINT
    ports:
      - 3001:3001
  loopback:
    build: ./loopback
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://dirt:password@database:5432/dirt?ssl=false
      - PORT=3002
      - ROOT_ADDRESS
      - INFURA_ENDPOINT
    ports:
      - 3002:3002
    depends_on:
      - database
    volumes:
      - ./tools/scripts:/usr/src/app/scripts
    command:
      - /bin/sh
      - -c
      - |
        ./scripts/wait-for-it.sh -s -t 30 database:5432
        npm start
