version: '3.7'
services:
  express:
    build: ./express
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ROOT_ADDRESS=0xDb1E8F93854cbC9272dA69544Fc62E5d4511c7D1
      - INFURA_ENDPOINT
    ports:
      - 3001:3001
